# See https://upptime.js.org/docs/configuration

# Owner and repository name
owner: fairpm # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

# Sites to monitor
sites:
  - name: FAIR
    url: https://fair.pm
    assignees:
      - rmccue
  - name: AspirePress
    url: https://aspirepress.org/
    assignees:
      - chuckadams

# Status website configuration
status-website:
  # When the status website is hosted on a custom domain, uncomment the `cname` line and set it to the custom domain name.
  # cname: status.fair.pm
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/fairpm/status/master/assets/logo.svg
  name: FAIR Project
  introTitle: "**FAIR** is a open-source distribution package manager for [WordPress](https://wordpress.org)."
  introMessage: "This is the status page for the FAIR Project."
  navbar:
    - title: Status
      href: https://fairpm.github.io/status
    - title: FAIR
      href: https://fair.pm
    - title: AspirePress
      href: https://aspirepress.org/
    - title: WordPress
      href: https://wordpress.org/
    - title: GitHub
      href: https://github.com/fairpm/status
  theme: light
  themeUrl: https://fairpm.github.io/status/fair-theme.css
  scripts:
    - src: https://fairpm.github.io/status/assets/datetime.js
  customFootHtml: "<p>All times are relative to the viewer's timezone. Current time: <span id='datetimeDisplay'></span></p>"
