# Change these first
owner: fairpm # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: FAIR
    url: https://fair.pm
    assignees:
      - rmccue
  - name: AspirePress
    url: https://aspirepress.org/
    assignees:
      - chuckadams

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/fairpm/status/master/assets/logo.svg
  name: FAIR Project
  introTitle: "**FAIR** is a open-source distribution package manager for [WordPress](https://wordpress.org)."
  introMessage: "This is the status page for the FAIR Project."
  navbar:
    - title: Status
      href: https://fairpm.github.io/status
    - title: FAIR
      href: https://fair.pm
    - title: AspirePress
      href: https://aspirepress.org/
    - title: WordPress
      href: https://wordpress.org/
    - title: GitHub
      href: https://github.com/fairpm/status
  theme: light
  themeUrl: https://fairpm.github.io/status/fair-theme.css

# Custom commit messages with DCO signatures
# GitHub bot email addresses follow the pattern: {bot-id}+{bot-name}@users.noreply.github.com
# This MAY fail if the bot changes, or GitHub changes the pattern.
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]\n\nSigned-off-by: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]\n\nSigned-off-by: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]\n\nSigned-off-by: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]\n\nSigned-off-by: Upptime Bot <73812536+upptime-bot@users.noreply.github.com>"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
