# See https://upptime.js.org/docs/configuration

# Owner and repository name
owner: fairpm
repo: status

# Sites to monitor
sites:
  - name: FAIR
    url: https://fair.pm
    icon: https://status.fair.pm/favicon.ico
    assignees:
      - rmccue,ipstenu,chuckadams
  - name: FAIR API
    url: https://api.fair.pm/
    icon: https://status.fair.pm/favicon.ico
    assignees:
      - rmccue,ipstenu,chuckadams
  - name: AspireCloud.net (Production)
    url: https://api.aspirecloud.net/
    assignees:
      - chuckadams
  - name: AspireCloud.io (Staging)
    url: https://api.aspirecloud.io/
    assignees:
      - chuckadams

# Status website configuration
status-website:
  cname: status.fair.pm
  logoUrl: https://status.fair.pm/logo.svg
  name: FAIR Project
  introTitle: "**FAIR.pm** is a groundbreaking way of distributing software from a decentralized group of repositories."
  introMessage: "This is the status page for the FAIR Project and its associated services."
  navbar:
    - title: FAIR
      href: https://fair.pm
  theme: light
  themeUrl: https://status.fair.pm/fair-theme.css
  scripts:
    - src: https://status.fair.pm/datetime.js
  customHeadHtml: "<div class='timezones'><p>All times listed are relative to the viewer's timezone. Current time: <span id='datetimeDisplay'></span></p></div>"
