# Change these first
owner: fairpm # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: FAIR
    url: https://fair.pm
    assignees:
      - rmccue
  - name: AspirePress
    url: https://aspirepress.org/
    assignees:
      - chuckadams

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/fairpm/status/master/assets/logo.svg
  name: FAIR Project
  introTitle: "**FAIR** is a open-source distribution package manager for [WordPress](https://wordpress.org)."
  introMessage: "This is the status page for the FAIR Project."
  navbar:
    - title: Status
      href: https://fairpm.github.io/status
    - title: FAIR
      href: https://fair.pm
    - title: AspirePress
      href: https://aspirepress.org/
    - title: WordPress
      href: https://wordpress.org/
    - title: GitHub
      href: https://github.com/fairpm/status
  theme: light
  themeUrl: https://fairpm.github.io/status/fair-theme.css
  js: "window.onload = function() { document.getElementById('datetimeDisplay').innerHTML = new Date().toLocaleString(); }"
  customBodyHtml: "<p>All times are relative to the viewer's timezone. Current time: <span id='datetimeDisplay'></span></p>"
# See https://upptime.js.org/docs/configuration
